name: tpms_app
description: "A TPMS Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.32.7
  provider: ^6.1.2
  syncfusion_flutter_charts: ^25.2.6
  cupertino_icons: ^1.0.6
  logger: ^2.3.0
  permission_handler: ^11.3.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/travel.png
